services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dantaskmanager-backend
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS:-http://+:8080}
      ConnectionStrings__DefaultConnection: Server=db,${DB_PORT:-1433};Database=${DB_NAME:-DanTaskManager};User Id=${DB_USER:-sa};Password=${DANTASKMANAGER_DB_PASSWORD:-Your_strong_Password123};Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dantaskmanager-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dantaskmanager-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DANTASKMANAGER_DB_PASSWORD:-Your_strong_Password123}
    ports:
      - "${DB_PORT:-1433}:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
